modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="moddymcmodface"
version="1.0.0"
displayName="Moddy McModface"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Meh-Vah'd Jukaar, MCreator"

[[dependencies.moddymcmodface]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




