modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="moddymcmodface"
version="alpha 0.6.3 WIP"
displayName="Supplementaries"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Meh-Vah'd Jukaar, MCreator"
description='''
Random blocks that I wanted to add to vanilla minecraft. Enjoy
'''

[[dependencies.moddymcmodface]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




